#!/bin/bash

i=$1
src=$2
user=$3
ip=$4
dest=$5

transfert() {

    if [ ! -z "$i" ] && [ ! -z "$src" ] && [ ! -z "$user" ] && [ ! -z "$ip" ] && [ ! -z "$dest" ] ; then
        if [ "$i" == "O" ]; then
            rsync -e ssh -avz --delete-after $src $user@$ip:$dest
        else
            rsync -e ssh -avz $src $user@$ip:$dest
        fi
        exit
    fi

    echo "Vous n'avez pas rentré tout les parametres, voulez vous continer O / N ?"
    read ok

    if [ "$ok" != "O" ] && [ "$ok" != "o" ]; then
        exit
    fi

    echo "Voulez restaurer le dossier destination O / N ?"
    read i

    echo "Veuillez saisir votre dossier source"
    read src

    echo "Veuillez saisir votre user ssh"
    read user

    echo "Veuillez saisir votre ip ssh"
    read ip

    echo "Veuillez saisir votre dossier destinaiton"
    read $dest

    if [ ! -z "$i" ] && [ ! -z "$src" ] && [ ! -z "$user" ] && [ ! -z "$ip" ] && [ ! -z "$dest" ] ; then
        if [ "$i" == "O" ]; then
            rsync -e ssh -avz --delete-after $src $user@$ip:$dest
        else
            rsync -e ssh -avz $src $user@$ip:$dest
        fi

    else
        echo "Vous n'avez pas rentré toutes les valeurs.. Voulez vous continuer avec la commande de base ?"
        read check

        if [ "$check" == "O" ]; then
        	rsync -e ssh -avz /home/source user@ip_du_serveur:/dossier/destination/
        else
            exit
        fi
    fi

}



#LANCEMENT DU SCRIPT

show_usage() {

    echo "Utilisation de la commande :"
    echo ""
    echo "Remarque: Il vaut mieux utiliser des chemins relatifs."
    echo ""
    echo "        ./script  <1> <2> <3> <4> <5>"
    echo ""
	echo "1: Check delete dossier destination --delete-after O = oui 1 = non"
	echo "2: Dossier source"
	echo "3: Nom user SSH"
    echo "4: IP SSH"
    echo "5: Dossier destination"
	echo ""
    echo ""
}

#LANCEMENT DU SCRIPT

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then

    show_usage

else
	#PRESETS
	
    transfert
fi